---
title: "tables_figures"
output:
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
library(knitr)
library(kableExtra)
library(purrr)
library(furrr)
library(boot)
library(lme4)
library(ICC) 
library(dotwhisker)
library(broom)
library(car)
library(reshape2)
library(sjPlot)
library(readxl)
library(broom.mixed)
library(bbmle)
library(glmmTMB)
library(performance)
library(MASS)
library(mgcv)
library(gridExtra)
library(tableone)
library(corrr)
library(psych)
library(zoo)
library(flextable)
library(clipr)

```

Annual models from DMED data.



## Load  data
```{r load_datasets, message = FALSE}

hsi_data <-
  read_rds("data/hsi_data.rds")

```


```{r}

#inspect
hsi_data %>% 
  filter(type %in% "Hospitalizations", 
         year %in% "2011",
         site_name %in% "Fort Hood") %>% 
  arrange(desc(value))


hsi_data %>% 
  summary()
```


```{r}

# Plots of heat indices over time
hsi_data %>% 
  filter(type %in% "Hospitalizations") %>% 
  ggplot(aes(x = year, y = value, color = site_name)) +
    geom_point() +
    geom_smooth(method = lm, se = FALSE, size = 0.5) +
  facet_wrap(~index, scale = "free") + 
  theme_bw()

#ggsave("output/indices_by_site_name.png")


# grayscale plot - no legend

# Plots of heat indices over time
hsi_data %>% 
  filter(type %in% "Hospitalizations") %>% 
  mutate(index = dplyr::recode(index, mean_tmp = "Mean Tmp",
                          mean_hi = "Mean HI",
                          mean_wbgt = "Mean WBGT",
                          max_tmp = "Max Tmp",
                          max_hi = "Max HI",
                          max_wbgt = "Max WBGT",
                          mean_tmp_may_sep = "Mean Tmp HS",
                          mean_hi_may_sep = "Mean HI HS",
                          mean_wbgt_may_sep = "Mean WBGT HS",
                          max_tmp_may_sep = "Max Tmp HS",
                          max_hi_may_sep = "Max HI HS",
                          max_wbgt_may_sep = "Max WBGT HS",
                          hours_tmp_gt90 = "Hrs Tmp > 90",
                          hours_tmp_gt100 = "Hrs Tmp > 100",
                          hours_hi_gt90 = "Hrs HI > 90",
                          hours_hi_gt105 = "Hrs HI > 105",
                          hours_wbgt_gt85 = "Hrs WBGT > 85",
                          hours_wbgt_gt90 = "Hrs WBGT > 90",
                          tmp_anomaly = "Tmp Anomaly",
                          hi_anomaly = "HI Anomaly",
                          wbgt_anomaly = "WBGT Anomaly",
                          days_tmp_gt1sd = "Days Tmp > 1 SD",
                          days_hi_gt1sd = "Days HI > 1 SD",
                          days_wbgt_gt1sd = " Days WBGT > 1 SD",
                          tmp_anomaly_may_sep = "Tmp Anomaly HS",
                          hi_anomaly_may_sep = "HI Anomaly HS",
                          wbgt_anomaly_may_sep = "WBGT Anomaly HS",
                          days_tmp_gt1sd_may_sep = "Days Tmp > 1 SD HS",
                          days_hi_gt1sd_may_sep = "Days HI > 1 SD HS",
                          days_wbgt_gt1sd_may_sep = "Days WBGT > 1 SD HS")) %>% 
  ggplot(aes(x = year, y = value)) +
    geom_point(size = 0.75) +
    geom_smooth(aes(group = site_name), method = lm, se = FALSE, size = 0.25, color = "gray") +
    geom_smooth(method = lm, se = FALSE, size = 0.5, color = "blue") +
    facet_wrap(~index, scale = "free", ncol = 5) + 
  theme_bw() +
  theme(strip.text = element_text(
    size = 8)) +
  labs(x = "Year",
       y = "Index value")

```



## Tables

```{r}

# Table 1: HSI outcomes

hsi_data %>% 
  filter(index %in% "mean_tmp") %>% 
  dplyr::select(site_name, type, year, count, rate) %>% 
  group_by(site_name, type) %>%
  summarise(mean_count = mean(count),
            sd_count = sd(count),
            mean_rate = mean(rate),
            sd_rate = sd(rate)) %>% 
  pivot_wider(names_from = type, values_from = c(mean_count:sd_rate))


# Table 2: Indices of Heat

index_stats <-
  hsi_data %>% 
    filter(type %in% "Hospitalizations") %>% 
    dplyr::select(site_name, index, year, value) %>% 
    group_by(site_name, index) %>%
    summarise(mean_value = mean(value),
              sd_value = sd(value)) %>%
    mutate(value = paste0(round(mean_value, 2)," ", "(", round(sd_value, 2), ")")) %>% 
    dplyr::select(site_name, index, value) %>% 
    pivot_wider(names_from = index, values_from = value) 


index_stats

# clipr::write_last_clip()


## Indices Table in Celsius

index_stats_c <-
  hsi_data %>% 
    filter(type %in% "Hospitalizations") %>% 
    dplyr::select(site_name, index, year, value) %>% 
    mutate(value_c = (5/9) * (value - 32)) %>% 
    group_by(site_name, index) %>%
    summarise(mean_value = mean(value_c),
              sd_value = sd(value_c)) %>%
    mutate(value = paste0(round(mean_value, 2)," ", "(", round(sd_value, 2), ")")) %>% 
    dplyr::select(site_name, index, value) %>% 
    pivot_wider(names_from = index, values_from = value) 


index_stats_c

# clipr::write_last_clip()



```


## Temperature over time models

```{r}

tmp_lm_function = function(df) {
  df %>%
    lm(value ~ year, data = .)
}



# Slope estimate
tmp_slopes <-
  hsi_data %>% 
    filter(type %in% "Hospitalizations") %>% 
    nest(data = -c(site_name, index)) %>% 
    mutate(lm_tmp = map(data, tmp_lm_function),
           tidy =   map(lm_tmp, broom::tidy),
           glance = map(lm_tmp, broom::glance))



# Temperature slope estimates (1991-2018)
tmp_slopes %>% 
    unnest(tidy) %>%
    dplyr::select(site_name, index, term:p.value) %>% 
    filter(term %in% "year") 


# Mean annual indices


# Temperature slope estimates (1991-2018)
tmp_slopes %>% 
    unnest(tidy) %>%
    dplyr::select(site_name, index, term:p.value) %>% 
    filter(term %in% "year", 
           index %in% c("mean_tmp", "mean_hi","mean_wbgt", 
                          "mean_tmp_may_sep", "mean_hi_may_sep", "mean_wbgt_may_sep")) %>% 
  arrange(estimate) %>% as.data.frame()

tmp_slopes %>% 
    unnest(tidy) %>%
    dplyr::select(site_name, index, term:p.value) %>% 
    filter(term %in% "year", 
           index %in% c("mean_tmp", "mean_hi","mean_wbgt", 
                          "mean_tmp_may_sep", "mean_hi_may_sep", "mean_wbgt_may_sep")) %>% 
  arrange(desc(p.value)) %>% View()

# Significant positive slopes
tmp_slopes %>% 
    unnest(tidy) %>%
    dplyr::select(site_name, index, term:p.value) %>% 
    filter(term %in% "year",
           p.value < 0.05) %>% 
    arrange(desc(estimate)) %>% as.data.frame()


tmp_slopes %>% 
    unnest(tidy) %>%
    filter(term %in% "year") %>% 
    group_by(index) %>% 
    ggplot() +
      geom_boxplot(aes(x = reorder(index, estimate), y = estimate)) +
      coord_flip()


# p-values    
hsi_data %>% 
  filter(type %in% "Hospitalizations") %>% 
  nest(data = -c(site_name, index)) %>%  
  mutate(lm_tmp = map(data, tmp_lm_function),
         tidy =   map(lm_tmp, broom::tidy),
         glance = map(lm_tmp, broom::glance)) %>% 
  unnest(tidy) %>% 
  filter(term %in% "year") %>% 
  group_by(index) %>% 
  ggplot() +
    geom_boxplot(aes(x = reorder(index, p.value), y = p.value)) +
    geom_hline(yintercept = 0.05, color = "blue") +
    coord_flip() 

```



## Plot HSI

```{r}
plot_amb_hsi <-
  hsi_data %>% 
    filter(type == "Ambulatory Data") %>% 
   ggplot(aes(x = year, y = rate, color = site_name)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Army Ambulatory Rates - HSI",
        x = "Year",
        y = "All ICD rate (per 1,000 persons per year)"
      ) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))


plot_hosp_hsi <-
  hsi_data %>% 
    filter(type == "Hospitalizations") %>% 
   ggplot(aes(x = year, y = rate, color = site_name)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Army Hospitalization Rates - HSI",
        x = "Year",
        y = "All ICD rate (per 1,000 persons per year)"
      ) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))



plot_rme_hsi <-
  hsi_data %>% 
    filter(type == "Reportable Events") %>% 
   ggplot(aes(x = year, y = rate, color = site_name)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Army Reportable Event Rates - HSI",
        x = "Year",
        y = "All ICD rate (per 1,000 persons per year)"
      ) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))

gridExtra::grid.arrange(plot_amb_hsi, plot_hosp_hsi, plot_rme_hsi, nrow = 1)




# Facet wrap

# HSI
 hsi_data %>% 
   ggplot(aes(x = year, y = rate, color = site_name)) +
      geom_point() +
      geom_line() +
      labs(
        title = "Heat Stress Illness Rates",
        x = "Year",
        y = "HSI rate (per 1,000 persons per year)"
      ) +
      facet_grid(~type) +
      theme_bw() +
      theme(strip.text = element_text(size = 6)) +
      theme(axis.text.x = element_text(angle = 90, hjust = 1))



```

## By site_name Tables


```{r}

#indices

wider_fun = function(df) {
  pivot_wider(df, names_from = year, values_from = value)
}



# get group keys
group_name <- hsi_data %>% 
  group_keys(site_name) %>% 
  .$site_name


index_tables <-    
  hsi_data %>%
    filter(type %in% "Hospitalizations",
           year >= 2008) %>%
    mutate(value = format(round(value, 2), nsmall = 2)) %>% 
    dplyr::select(site_name, index, year, value) %>%
    group_split(site_name, keep = FALSE) %>%
    purrr::map(wider_fun) %>% 
    setNames(group_name)



index_tables[[1]] %>% 
  flextable() %>% 
  flextable::fontsize(., part = "all", size = 6) %>% 
  flextable::padding(., padding = 0, part = "body") %>%
  flextable::bold(., part = "header") %>% 
  flextable::autofit() %>% 
  print(., preview = "docx")



```


